version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: build-dotnet-app
          command: dotnet build